services:
  morsebrowser:
    build:
      context: .
    image: morsebrowser:local
    ports:
      - "19090:8080"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
